apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keepalived.fullname" . }}-config
  labels:
    {{- include "keepalived.labels" . | nindent 4 }}
data:
  keepalived.conf: |
    vrrp_instance VI_1 {
        state BACKUP
        interface {{ .Values.config.interface }}
        virtual_router_id {{ .Values.config.virtualRouterId }}
        priority 100
        authentication {
            auth_type AH
            auth_pass {{ .Values.config.password }}
        }
        virtual_ipaddress {
            {{ .Values.config.virtualIpAddress }}
        }
    }
